Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  config.vm.network "forwarded_port", guest: 8081, host: 8081


  config.vm.provider "virtualbox" do |vb|
    vb.name = "SampleVirtualMachine"
    vb.memory = "8192"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "bootstrap.sh", privileged: false
end