Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  for i in 8000..8080
    config.vm.network :forwarded_port, guest: i, host: i
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Continuous Integration Server"
    vb.memory = "8192"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "bootstrap.sh", privileged: false
end