web:  
  build: .
  ports:
    - "8081:8081"
  links:
    - db
db:
  image: postgres
  ports:
  - "5432:5432"
  environment:
    POSTGRES_USER: lewrang
    POSTGRES_PASSWORD: lewrang
    POSTGRES_DB: quotes